name: datetimepicker
version: 0.2.0
author: Johan Henselmans<johanhenselmans@gmail.com>
description: DateTime Input using a DateTime Picker Based on https://github.com/jrofurtado/datepicker.git
homepage: https://github.com/johanhenselmans/datetimepickerpolymer
dependencies:
  browser: any
  intl: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
